server {
    listen 80;
    server_name localhost;

    # Thư mục gốc chứa video trong container
    root /usr/share/nginx/html;

    # Cho phép hiển thị file video trực tiếp
    location / {
        try_files $uri $uri/ =404;
        autoindex on; # Bật liệt kê file (tùy chọn, tiện để debug)
    }
}
