server {
    listen 80;
    server_name thanhserver123.me;

    # Point to the shared volume
    root /usr/share/nginx/html;

    location / {
        autoindex on; # Allows you to see the file list in browser

        # Enable CORS for HLS Player
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length';

        # Standard HLS mime types
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }
    }
}