server {
    listen 80;
    server_name thanhserver123.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name thanhserver123.me;

    ssl_certificate /etc/nginx/certs/fullchain.pem; 
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    # Point to the shared volume
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.(m3u8|ts)$ {
        types {
            application/vnd.apple.mpegurl m3u8;
            video/mp2t ts;
        }

        # Enable CORS for HLS Player
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length';

    }

    location /api/ {
        rewrite ^/api/(.*) /$1 break;

        proxy_pass http://128.199.90.123:8081;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws/ {
            proxy_pass http://128.199.90.123:8081;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
    }
}
