server {
    listen 80;
    server_name thanhserver123.me;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name thanhserver123.me;

    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    client_max_body_size 100M;
    # Point to the shared volume
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
