input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["channel-svc.public.streams"]
    group_id => "logstash_debezium_stream_consumer"
    auto_offset_reset => "earliest"
    codec => "json"
  }
}

filter {
  ruby {
    code => '
      p = event.get("payload")
      if p.nil?
        event.cancel
        return
      end

      op = p["op"]

      case op
      when "d"
        before = p["before"] || {}
        event.set("[@metadata][es_action]", "delete")
        event.set("[@metadata][doc_id]", before["id"])
        event.remove("schema")
        event.remove("payload")

      when "c", "u", "r"  # create / update / snapshot read
        after = p["after"] || {}
        event.set("[@metadata][es_action]", "index")
        event.set("[@metadata][doc_id]", after["id"])

        event.remove("schema")
        event.remove("payload")
        after.each { |k, v| event.set(k, v) }

      else
        # Unknown op -> drop to be safe
        event.cancel
      end
    '
  }

  elasticsearch {
    hosts => ["http://es:9200"]
    index => "channels"
    query => "id:%{[channel_id]}"
    sort => "id:desc"
    fields => {
      "title" => "channel_title"
    }
    tag_on_failure => ["channel_enrich_failed"]
  }

  elasticsearch {
    hosts => ["http://es:9200"]
    index => "categories"
    query => "id:%{[category_id]}"
    sort => "id:desc"
    fields => {
      "title" => "category_title"
    }
    tag_on_failure => ["category_enrich_failed"]
  }

  mutate {
    remove_field => ["@version", "host", "message", "@timestamp", "event", "created_at", "updated_at"]
    convert => {
      "subscription_count" => "integer"
      "is_live"            => "boolean"
    }
  }
}

output {
  elasticsearch {
    hosts             => ["http://es:9200"]
    index             => "streams"
    action            => "%{[@metadata][es_action]}"
    document_id       => "%{[@metadata][doc_id]}"
  }
}