services:
  traefik:
    image: traefik:v3.5
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/certs:/etc/traefik/certs
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml

  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - ../docs/api.yml:/spec/openapi.yml
    environment:
      SWAGGER_JSON: /spec/openapi.yml
      BASE_URL: /docs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swagger-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/docs`)"
      - "traefik.http.routers.swagger-router.entrypoints=websecure"
      - "traefik.http.routers.swagger-router.tls=true"
      - "traefik.http.services.swagger-service.loadbalancer.server.port=8080"

  ome:
    image: airensoft/ovenmediaengine:latest
    container_name: ome
    volumes:
      - ./ovm-conf/Server.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml
      - ome_recordings:/mnt/recordings
    ports:
      - "9999:9999/udp"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ome-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/app`)"
      - "traefik.http.routers.ome-router.entrypoints=websecure"
      - "traefik.http.routers.ome-router.tls=true"
      - "traefik.http.services.ome-service.loadbalancer.server.port=3333"

  nginx-vod:
    image: nginx:alpine
    container_name: nginx-vod
    volumes:
      - ./nginx/internal.conf:/etc/nginx/conf.d/default.conf
      - ome_recordings:/usr/share/nginx/html/recordings
    depends_on:
      - ome
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx-vod-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/recordings`)"
      - "traefik.http.routers.nginx-vod-router.entrypoints=websecure"
      - "traefik.http.routers.nginx-vod-router.tls=true"
      - "traefik.http.services.nginx-vod-service.loadbalancer.server.port=80"

  pg:
    image: postgres:18rc1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - ./initdb/init_db.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      dockerfile: ./auth-service/build/Dockerfile
      context: ..
    environment:
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth
      SERVER_PORT: 8080
      USER_SESSION_TTL: 720h
      JWT_SECRET_KEY: supersecretkey1233456
      JWT_ACCESS_TOKEN_TTL: 24h
      JWT_REFRESH_TOKEN_TTL: 168h
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-router.entrypoints=websecure"
      - "traefik.http.routers.auth-router.tls=true"
      - "traefik.http.routers.user-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/users`)"
      - "traefik.http.routers.user-router.entrypoints=websecure"
      - "traefik.http.routers.user-router.tls=true"
      - "traefik.http.middlewares.custom-auth.forwardauth.address=http://auth-service:8080/auth/verify"
      - "traefik.http.middlewares.custom-auth.forwardauth.authResponseHeaders=X-User-Id,X-User-Role"
      - "traefik.http.services.auth-service.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true"
      - "traefik.http.routers.auth-router.middlewares=cors"
      - "traefik.http.routers.user-router.middlewares=cors"

  channel-service:
    build:
      dockerfile: ./channel-service/build/Dockerfile
      context: ..
    environment:
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: channel
      SERVER_PORT: 8080
      SERVER_CHAT_SERVER_URL: http://chat-service:8001
      SERVER_SRT_SERVER_URL: srt://128.199.90.123:9999
      SERVER_HLS_SERVER_URL: https://thanhserver123.me
      SERVER_RECORD_SERVER_URL: https://thanhserver123.me
      ELASTICSEARCH_ADDRESSES: http://es:9200
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin12345
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: notification-events
    depends_on:
      pg:
        condition: service_healthy
      minio:
        condition: service_healthy
      init-services:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.channel-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/channels`)"
      - "traefik.http.routers.channel-router.entrypoints=websecure"
      - "traefik.http.routers.channel-router.tls=true"
      - "traefik.http.routers.channel-router.middlewares=cors,custom-auth"
      - "traefik.http.routers.stream-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/streams`)"
      - "traefik.http.routers.stream-router.entrypoints=websecure"
      - "traefik.http.routers.stream-router.tls=true"
      - "traefik.http.routers.stream-router.middlewares=cors,custom-auth"
      - "traefik.http.routers.category-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/categories`)"
      - "traefik.http.routers.category-router.entrypoints=websecure"
      - "traefik.http.routers.category-router.tls=true"
      - "traefik.http.routers.category-router.middlewares=cors,custom-auth"
      - "traefik.http.routers.public-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/public`)"
      - "traefik.http.routers.public-router.entrypoints=websecure"
      - "traefik.http.routers.public-router.tls=true"
      - "traefik.http.routers.public-router.middlewares=cors"
      - "traefik.http.services.channel-service.loadbalancer.server.port=8080"

  notification-service:
    build:
      dockerfile: ./notification-service/build/Dockerfile
      context: ..
    environment:
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: notification
      SERVER_PORT: 8080
      KAFKA_BROKERS: kafka:9092
      KAFKA_GROUP_ID: notification-consumers
      KAFKA_TOPIC: notification-events
    depends_on:
      pg:
        condition: service_healthy
      init-services:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notification-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/notifications`)"
      - "traefik.http.routers.notification-router.entrypoints=websecure"
      - "traefik.http.routers.notification-router.tls=true"
      - "traefik.http.routers.notification-router.middlewares=cors,custom-auth"
      - "traefik.http.services.notification-service.loadbalancer.server.port=8080"

  donation-service:
    build:
      dockerfile: ./donation-service/build/Dockerfile
      context: ..
    environment:
      POSTGRES_HOST: pg
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: donation
      SERVER_PORT: 8080
      SERVER_FRONTEND_REDIRECT_URL: "https://thanhserver123.me/payment-result"

      KAFKA_BROKERS: kafka:9092
      KAFKA_CHANNEL_TOPIC: channel-svc.public.channels
      KAFKA_CHANNEL_CONSUMER_GROUP: abcdxyz
      KAFKA_PUBLISH_DONATE_TOPIC: donation-events

      VNPAY_TMN_CODE: 15ZMLXYR
      VNPAY_HASH_SECRET: RT19URTSYGGGZTLAHFGXZS8YASN7HIV0
      VNPAY_PAY_URL: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      VNPAY_RETURN_URL: https://thanhserver123.me/vnpay/handle-payment
    depends_on:
      pg:
        condition: service_healthy
      init-services:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.donation-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/donations`)"
      - "traefik.http.routers.donation-router.entrypoints=websecure"
      - "traefik.http.routers.donation-router.tls=true"
      - "traefik.http.routers.donation-router.middlewares=cors,custom-auth"
      - "traefik.http.routers.wallet-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/wallets`)"
      - "traefik.http.routers.wallet-router.entrypoints=websecure"
      - "traefik.http.routers.wallet-router.tls=true"
      - "traefik.http.routers.wallet-router.middlewares=cors,custom-auth"
      - "traefik.http.routers.vnpay-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/vnpay`)"
      - "traefik.http.routers.vnpay-router.entrypoints=websecure"
      - "traefik.http.routers.vnpay-router.tls=true"
      - "traefik.http.routers.vnpay-router.middlewares=cors"
      - "traefik.http.services.donation-service.loadbalancer.server.port=8080"

  chat-service:
    build:
      dockerfile: ./chat-service/build/Dockerfile
      context: ..
    environment:
      SERVER_ADDR: ":8001"
      JWT_SECRET: "supersecretkey1233456"
      CORS_ORIGINS: "*"
      CORS_ALLOW_CREDENTIALS: "true"
      DB_DSN: "postgres://admin:123456@pg:5432/chatdb?sslmode=disable"
      KAFKA_BROKERS: kafka:9092
      KAFKA_CHAT_CONSUMER_GROUP: chat-service-group
      KAFKA_PUBLISH_DONATE_TOPIC: donation-events
    ports:
      - "8001:8001"
    depends_on:
      pg:
        condition: service_healthy
      init-services:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/chat`)"
      - "traefik.http.routers.chat-router.entrypoints=websecure"
      - "traefik.http.routers.ws-router.rule=Host(`thanhserver123.me`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.ws-router.entrypoints=websecure"
      - "traefik.http.services.chat-service.loadbalancer.server.port=8001"

  moderation-service:
    build: ../moderation-service
    container_name: moderation-service
    env_file:
      - ../moderation-service/.env
    ports:
      - "5000:5000"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      node.name: es
      cluster.name: es-docker-cluster
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      xpack.security.enabled: false
      discovery.type: single-node
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    environment:
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - "5601:5601"

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  source-connector:
    image: debezium/connect:3.0.0.Final
    depends_on:
      kafka:
        condition: service_healthy
      pg:
        condition: service_healthy
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: source-connector-configs
      OFFSET_STORAGE_TOPIC: source-connector-offsets
      STATUS_STORAGE_TOPIC: source-connector-status
      BOOTSTRAP_SERVERS: kafka:9092
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_REST_ADVERTISED_HOST_NAME: source-connector
    healthcheck:
      test: [ "CMD", "curl", "--fail", "--silent", "--output", "/dev/null", "http://localhost:8083/connectors" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  logstash:
    image: logstash:9.0.2
    depends_on:
      init-services:
        condition: service_completed_successfully
    volumes:
      - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash/pipeline/channel.conf:/usr/share/logstash/pipeline/channel.conf
      - ./logstash/pipeline/stream.conf:/usr/share/logstash/pipeline/stream.conf
      - ./logstash/pipeline/category.conf:/usr/share/logstash/pipeline/category.conf
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"

  init-services:
    image: confluentinc/cp-kafka:7.2.15
    container_name: init-services
    depends_on:
      kafka:
        condition: service_healthy
      source-connector:
        condition: service_healthy
      es:
        condition: service_healthy
    volumes:
      - ./setup:/setup
    command: [ "bash", "/setup/setup.sh" ]

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/docker-certs:/etc/nginx/certs

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data

volumes:
  ome_recordings:
  postgres_data:
  minio_data:
